# Generated by Django 5.2.14 on 2026-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(max_length=32, unique=True)),
                ('domain', models.CharField(max_length=64)),
                ('perceiver_id', models.CharField(max_length=64)),
                ('planner_id', models.CharField(max_length=64)),
                ('guardian_id', models.CharField(blank=True, max_length=64)),
                ('perception_result', models.JSONField(default=dict)),
                ('action_plan', models.JSONField(default=dict)),
                ('guardian_approved', models.BooleanField(default=True)),
                ('guardian_reason', models.TextField(blank=True)),
                ('outcome', models.JSONField(blank=True, default=dict)),
                ('reward', models.FloatField(blank=True, null=True)),
                ('tier_used', models.CharField(default='MEDIUM', max_length=8)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', 'created_at'], name='decisions_d_domain_428281_idx')],
            },
        ),
    ]
