# Generated by Django 5.2.14 on 2026-05-14 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A2AMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64, unique=True)),
                ('from_agent', models.CharField(max_length=64)),
                ('to_agent', models.CharField(max_length=64)),
                ('message_type', models.CharField(max_length=32)),
                ('domain', models.CharField(default='generic', max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['from_agent', 'timestamp'], name='agents_a2am_from_ag_39ed83_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('perceiver', 'Perceiver'), ('planner', 'Planner'), ('recoverer', 'Recoverer'), ('guardian', 'Guardian')], max_length=16)),
                ('domain', models.CharField(default='generic', max_length=64)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('degraded', 'Degraded'), ('quarantined', 'Quarantined')], default='idle', max_length=16)),
                ('current_tier', models.CharField(choices=[('HEAVY', 'Heavy'), ('MEDIUM', 'Medium'), ('LIGHT', 'Light')], default='MEDIUM', max_length=8)),
                ('version', models.CharField(default='0.1.0', max_length=16)),
                ('trust_tier', models.CharField(default='high', max_length=8)),
                ('total_calls', models.IntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('error_count', models.IntegerField(default=0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['role', 'domain'],
                'indexes': [models.Index(fields=['role', 'domain'], name='agents_agen_role_cc53b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64)),
                ('action_id', models.CharField(max_length=128)),
                ('action_params', models.JSONField(default=dict)),
                ('context_snapshot', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('tier_used', models.CharField(default='MEDIUM', max_length=8)),
                ('guardian_approved', models.BooleanField(default=True)),
                ('outcome_reward', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='agents.agentinstance')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', 'created_at'], name='agents_agen_domain_47a99f_idx')],
            },
        ),
    ]
