# Generated by Django 5.2.14 on 2026-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=64, unique=True)),
                ('agent_id', models.CharField(max_length=64)),
                ('domain', models.CharField(default='generic', max_length=64)),
                ('action', models.JSONField(default=dict)),
                ('context', models.JSONField(default=dict)),
                ('verdict', models.CharField(choices=[('approve', 'Approve'), ('warn', 'Warn'), ('block', 'Block'), ('quarantine', 'Quarantine')], default='approve', max_length=16)),
                ('violations', models.JSONField(default=list)),
                ('audit_hash', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent_id', 'timestamp'], name='audit_audit_agent_i_6280a0_idx'), models.Index(fields=['verdict', 'timestamp'], name='audit_audit_verdict_a53996_idx')],
            },
        ),
    ]
