# Generated by Django 5.2.14 on 2026-05-14 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('domain', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('mitigating', 'Mitigating'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('affected_agents', models.JSONField(default=list)),
                ('root_cause', models.TextField(blank=True)),
                ('recovery_plan', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['domain', 'status'], name='incidents_i_domain_dc33e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('actor', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='incidents.incident')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
